// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import React from "react";
import Providers from "../../providers"; 

export const metadata: Metadata = { 
  title: "EVSharing",
  description: "Generated by create next app",
=======

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EV-Co - AI Report Generator",
  description: "Phân tích dữ liệu sử dụng dịch vụ bằng AI",
>>>>>>> main
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="vi" suppressHydrationWarning> 
      <body>
        <Providers>
          <main>{children}</main> 
        </Providers>
      </body>
    </html>
  );
}
=======
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
>>>>>>> main
