import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {Geist, Geist_Mono} from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Providers from "../../providers";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="vi">
		<body>

		<Providers>
			{children}
		</Providers>

		</body>
		</html>
	);
}